### ISSUE TITLE
no clue

### ISSUE THREAD

**Issue by Jensdiep** [scholtzan/homebridge-rusty-spotify#3]
Sorry but I have no clue how to run the generate_config script. How do you run it?

Thanks!

**Comment by scholtzan** [comment]
You need to have [Python](https://www.python.org/) installed to run the script. The script also has one Python package as dependency which is easiest installed using [pip](https://pip.pypa.io/en/stable/installing/). Then you can just execute `pip install spotipy` on your command line and run the script by executing `./generate_config`.

Those steps should work for Linux and macOS. I'm not sure if there is more involved to execute the script in Windows.

**Comment by Jensdiep** [comment]
Thanks that makes sense!
Now I got this error:


`26-5-2020 18:10:01 Loaded plugin "homebridge-rusty-spotify".
26-5-2020 18:10:01 homebridge API version: 2.5
26-5-2020 18:10:04 Authorize to Spotify
26-5-2020 18:10:04 Authorize to Spotify
26-5-2020 18:10:04 Check playback state
26-5-2020 18:10:04 Check playback state
26-5-2020 18:10:04 (node:713) UnhandledPromiseRejectionWarning: RuntimeError: unreachable
26-5-2020 18:10:04 at __rust_start_panic (wasm-function[448]:0x2526e)
26-5-2020 18:10:04 at rust_panic (wasm-function[312]:0x247ac)
26-5-2020 18:10:04 at std::panicking::rust_panic_with_hook::h4e529e530989255b (wasm-function[160]:0x1fcc3)
26-5-2020 18:10:04 at rust_begin_unwind (wasm-function[234]:0x23170)
26-5-2020 18:10:04 at core::panicking::panic_fmt::h83dd057ea462878e (wasm-function[291]:0x2440f)
26-5-2020 18:10:04 at core::result::unwrap_failed::h6d70f69438bf9954 (wasm-function[219]:0x22a5f)
26-5-2020 18:10:04 at <std::future::GenFuture<T> as core::future::future::Future>::poll::hec2ec77bbe953909 (wasm-function[48]:0xbc4c)
26-5-2020 18:10:04 at wasm_bindgen_futures::task::singlethread::Task::run::h227f93bb34be8b61 (wasm-function[161]:0x1fd24)
26-5-2020 18:10:04 at wasm_bindgen_futures::queue::Queue::new::{{closure}}::hf30b50702b7523eb (wasm-function[152]:0x1f294)
26-5-2020 18:10:04 at <dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h999749d6f1213c6c (wasm-function[330]:0x24a4e)
26-5-2020 18:10:04 at __wbg_adapter_28 (/home/hoobs/.hoobs/node_modules/homebridge-rusty-spotify/homebridge_rusty_spotify.js:175:10)
26-5-2020 18:10:04 at real (/home/hoobs/.hoobs/node_modules/homebridge-rusty-spotify/homebridge_rusty_spotify.js:165:20)
26-5-2020 18:10:04 at processTicksAndRejections (internal/process/task_queues.js:97:5)
26-5-2020 18:10:04 (node:713) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
26-5-2020 18:10:04 (node:713) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`
